version: '3.8'

# Define networks first
networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: .
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    networks:
      - app-network
    hostname: imageserver.local
      
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  postgres_data: