#!/bin/bash -e

source /scripts/with-bigcontenv

# Command to start app
START_APP="uvicorn image_server.main:app --host 0.0.0.0 --port 8000"

# Ensure app is running from virtual environment
source activate env

echo "Starting application with command line: ${START_APP}"
exec s6-setuidgid asruser cd ${PYTHON_APP_FOLDER} ${START_APP}