-- Create the table
CREATE TABLE IF NOT EXISTS products (
    id INT PRIMARY KEY,
    title TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    image TEXT,
    rating_rate DECIMAL(3, 1),
    rating_count INT
);

-- Insert data into the table
INSERT INTO products (id, title, price, description, category, image, rating_rate, rating_count) VALUES
(1, 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 109.95, 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 'men''s clothing', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', 3.9, 120),
(2, 'Mens Casual Premium Slim Fit T-Shirts', 22.30, 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 'men''s clothing', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 4.1, 259),
(3, 'Mens Cotton Jacket', 55.99, 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 'men''s clothing', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 4.7, 500),
(4, 'Mens Casual Slim Fit', 15.99, 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', 'men''s clothing', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 2.1, 430),
(5, 'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 695.00, 'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.', 'jewelery', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', 4.6, 400),
(6, 'Solid Gold Petite Micropave', 168.00, 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 'jewelery', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 3.9, 70),
(7, 'White Gold Plated Princess', 9.99, 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...', 'jewelery', 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 3.0, 400),
(8, 'Pierced Owl Rose Gold Plated Stainless Steel Double', 10.99, 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 'jewelery', 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 1.9, 100),
(9, 'WD 2TB Elements Portable External Hard Drive - USB 3.0', 64.00, 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 'electronics', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 3.3, 203),
(10, 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 109.00, 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', 'electronics', 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 2.9, 470),
(11, 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor', 999.99, 'The Samsung CHG90 49-inch ultra-wide curved gaming monitor features a 144Hz refresh rate, 1ms response time, and HDR support, perfect for an immersive gaming experience.', 'electronics', 'https://fakestoreapi.com/img/71n2FQU5sDL._AC_SX679_.jpg', 4.5, 380),
(12, 'Logitech G Pro X Wireless Lightspeed Gaming Headset', 199.99, 'The Logitech G Pro X is a wireless gaming headset with LIGHTSPEED technology, delivering high-fidelity sound, comfortable memory foam ear pads, and a detachable microphone.', 'electronics', 'https://fakestoreapi.com/img/51KP-x_53dL._AC_SY879_.jpg', 4.7, 210),
(13, 'Apple iPhone 12 Pro Max (128GB) - Graphite', 1099.99, 'Apple iPhone 12 Pro Max with a 6.7-inch Super Retina XDR display, 128GB storage, A14 Bionic chip, and 5G capability.', 'electronics', 'https://fakestoreapi.com/img/61MBtKcRL7L._AC_SY679_.jpg', 4.8, 650),
(14, 'Sony WH-1000XM4 Wireless Noise-Canceling Headphones', 348, 'The Sony WH-1000XM4 offers premium noise-canceling performance, a long-lasting battery, and high-quality audio, perfect for work or leisure.', 'electronics', 'https://fakestoreapi.com/img/81cJ0jUzfYL._AC_SY879_.jpg', 4.6, 390),
(15, 'Dell XPS 13 9310 Laptop', 1449.99, 'The Dell XPS 13 9310 is a sleek and powerful ultrabook with a 13.4-inch 4K touchscreen, Intel Core i7 processor, and 16GB of RAM, ideal for professional use and entertainment.', 'electronics', 'https://fakestoreapi.com/img/61jWaQwDRZL._AC_SY879_.jpg', 4.7, 220),
(16, 'Bose QuietComfort 35 II Wireless Bluetooth Headphones', 299.99, 'Bose QuietComfort 35 II features world-class noise cancellation and high-quality sound for an immersive listening experience.', 'electronics', 'https://fakestoreapi.com/img/91g9OUZ64eL._AC_SY879_.jpg', 4.8, 310),
(17, 'Ninja Foodi 5-in-1 Air Fryer and Multi Cooker', 159.99, 'The Ninja Foodi 5-in-1 is an air fryer, pressure cooker, and multi-cooker in one, perfect for preparing a wide variety of meals with ease and speed.', 'home appliance', 'https://fakestoreapi.com/img/81aVwQ6zyOL._AC_SX679_.jpg', 4.5, 420),
(18, 'Instant Pot Duo 7-in-1 Electric Pressure Cooker', 89.99, 'The Instant Pot Duo is a 7-in-1 electric pressure cooker that offers multiple cooking functions, making it a versatile kitchen appliance for quick meals.', 'home appliance', 'https://fakestoreapi.com/img/71OeR7uScqL._AC_SY879_.jpg', 4.6, 560),
(19, 'Eureka NEU180A PowerSpeed Bagless Upright Vacuum Cleaner', 69.99, 'Eureka NEU180A PowerSpeed is a lightweight, powerful vacuum cleaner with a bagless design, ideal for cleaning carpets and hard floors with ease.', 'home appliance', 'https://fakestoreapi.com/img/71p5fb6BGML._AC_SY679_.jpg', 4.2, 650),
(20, 'Dyson V11 Torque Drive Cordless Vacuum Cleaner', 599.99, 'The Dyson V11 Torque Drive is a cordless vacuum with strong suction, up to 60 minutes of run time, and an LCD screen to display real-time performance data.', 'home appliance', 'https://fakestoreapi.com/img/71rQI2WZoLL._AC_SY879_.jpg', 4.7, 500);
